config/routes.rb
ShootrPrototype::Application.routes.draw do
  resources :matches
  resources :shooters
  match 'matches/register' => "matches#register"

  root :to => "home#index"

end

app/models/match.rb
class Match
  include Mongoid::Document
  include Mongoid::MultiParameterAttributes

  field :name, type: String
  field :date, type: Date
  field :time, type: Integer
  field :type, type: String
  field :number_of_squads, type: Integer
  field :number_of_stages, type: Integer

  has_and_belongs_to_many :shooters, :inverse_of => :matches, :class_name => 'Shooter' 
end

app/models/shooter.rb
class Shooter
  include Mongoid::Document
  field :name, type: String
  field :email, type: String

  has_and_belongs_to_many :matches
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  # GET /matches
  # GET /matches.json
  def index
    @matches = Match.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @matches }
    end
  end

  # GET /matches/1
  # GET /matches/1.json
  def show
    @match = Match.find(params[:id])
    @shooters = Shooter.where(:match_ids.nin => [@match.id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @match }
    end
  end

  # GET /matches/new
  # GET /matches/new.json
  def new
    @match = Match.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @match }
    end
  end

  # GET /matches/1/edit
  def edit
    @match = Match.find(params[:id])
  end

  def register
    @match = Match.find(params[:match_id])
    @shooter = Shooter.find(params[:shooter_id])
    @match.shooters.push(@shooter)

    redirect_to @match
  end

  # POST /matches
  # POST /matches.json
  def create
    @match = Match.new(params[:match])

    respond_to do |format|
      if @match.save
        format.html { redirect_to @match, notice: 'Match was successfully created.' }
        format.json { render json: @match, status: :created, location: @match }
      else
        format.html { render action: "new" }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /matches/1
  # PUT /matches/1.json
  def update
    @match = Match.find(params[:id])

    respond_to do |format|
      if @match.update_attributes(params[:match])
        format.html { redirect_to @match, notice: 'Match was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1
  # DELETE /matches/1.json
  def destroy
    @match = Match.find(params[:id])
    @match.destroy

    respond_to do |format|
      format.html { redirect_to matches_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/shooters_controller.rb
class ShootersController < ApplicationController
  # GET /shooters
  # GET /shooters.json
  def index
    @shooters = Shooter.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @shooters }
    end
  end

  # GET /shooters/1
  # GET /shooters/1.json
  def show
    @shooter = Shooter.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @shooter }
    end
  end

  # GET /shooters/new
  # GET /shooters/new.json
  def new
    @shooter = Shooter.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @shooter }
    end
  end

  # GET /shooters/1/edit
  def edit
    @shooter = Shooter.find(params[:id])
  end

  # POST /shooters
  # POST /shooters.json
  def create
    @shooter = Shooter.new(params[:shooter])

    respond_to do |format|
      if @shooter.save
        format.html { redirect_to @shooter, notice: 'Shooter was successfully created.' }
        format.json { render json: @shooter, status: :created, location: @shooter }
      else
        format.html { render action: "new" }
        format.json { render json: @shooter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /shooters/1
  # PUT /shooters/1.json
  def update
    @shooter = Shooter.find(params[:id])

    respond_to do |format|
      if @shooter.update_attributes(params[:shooter])
        format.html { redirect_to @shooter, notice: 'Shooter was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @shooter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shooters/1
  # DELETE /shooters/1.json
  def destroy
    @shooter = Shooter.find(params[:id])
    @shooter.destroy

    respond_to do |format|
      format.html { redirect_to shooters_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/shooters_helper.rb
module ShootersHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShootrPrototype</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<hr/>
<%= link_to "Shooters", shooters_path %><br/>
<%= link_to "Matches", matches_path %><br/>
</body>
</html>

app/views/matches/_form.html.erb
<%= form_for(@match) do |f| %>
  <% if @match.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
      <% @match.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :time %><br />
    <%= f.number_field :time %>
  </div>
  <div class="field">
    <%= f.label :type %><br />
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :number_of_squads %><br />
    <%= f.number_field :number_of_squads %>
  </div>
  <div class="field">
    <%= f.label :number_of_stages %><br />
    <%= f.number_field :number_of_stages %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/matches/edit.html.erb
<h1>Editing match</h1>

<%= render 'form' %>

<%= link_to 'Show', @match %> |
<%= link_to 'Back', matches_path %>

app/views/matches/index.html.erb
<h1>Listing matches</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Date</th>
    <th>Time</th>
    <th>Type</th>
    <th>Number of squads</th>
    <th>Number of stages</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @matches.each do |match| %>
  <tr>
    <td><%= match.name %></td>
    <td><%= match.date %></td>
    <td><%= match.time %></td>
    <td><%= match.type %></td>
    <td><%= match.number_of_squads %></td>
    <td><%= match.number_of_stages %></td>
    <td><%= link_to 'Show', match %></td>
    <td><%= link_to 'Edit', edit_match_path(match) %></td>
    <td><%= link_to 'Destroy', match, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Match', new_match_path %>

app/views/matches/new.html.erb
<h1>New match</h1>

<%= render 'form' %>

<%= link_to 'Back', matches_path %>

app/views/matches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @match.name %>
</p>

<p>
  <b>Date:</b>
  <%= @match.date %>
</p>

<p>
  <b>Time:</b>
  <%= @match.time %>
</p>

<p>
  <b>Type:</b>
  <%= @match.type %>
</p>

<p>
  <b>Number of squads:</b>
  <%= @match.number_of_squads %>
</p>

<p>
  <b>Number of stages:</b>
  <%= @match.number_of_stages %>
</p>
<hr/>
Registered Shooters:
<ul>
  <% @match.shooters.each do |shooter| %>
    <li><%= shooter.name %></li>
  <% end %>
</ul>
<hr/>


<%= link_to 'Edit', edit_match_path(@match) %> |
<%= link_to 'Back', matches_path %>
<%= form_tag({:action => "register"}) do %>
  Match: <%= hidden_field_tag :match_id, @match.id %>
  <%= @match.name %><br/>
  <%= select '', 'shooter_id', @shooters.map { |m| [m.name, m.id] } %><br />
  <%= submit_tag "Register shooter" %>
<% end %>

app/views/shooters/_form.html.erb
<%= form_for(@shooter) do |f| %>
  <% if @shooter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shooter.errors.count, "error") %> prohibited this shooter from being saved:</h2>

      <ul>
      <% @shooter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shooters/edit.html.erb
<h1>Editing shooter</h1>

<%= render 'form' %>

<%= link_to 'Show', @shooter %> |
<%= link_to 'Back', shooters_path %>

app/views/shooters/index.html.erb
<h1>Listing shooters</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @shooters.each do |shooter| %>
  <tr>
    <td><%= shooter.name %></td>
    <td><%= shooter.email %></td>
    <td><%= link_to 'Show', shooter %></td>
    <td><%= link_to 'Edit', edit_shooter_path(shooter) %></td>
    <td><%= link_to 'Destroy', shooter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Shooter', new_shooter_path %>

app/views/shooters/new.html.erb
<h1>New shooter</h1>

<%= render 'form' %>

<%= link_to 'Back', shooters_path %>

app/views/shooters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @shooter.name %>
</p>

<p>
  <b>Email:</b>
  <%= @shooter.email %>
</p>

Matches:
<ul>
  <% @shooter.matches.each do |match| %>
    <li><%= match.name %>
  <% end %>
</ul>

<%= link_to 'Edit', edit_shooter_path(@shooter) %> |
<%= link_to 'Back', shooters_path %>